name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # ---------- auth & checkout ----------
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      # ---------- Node & pnpm ----------
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org
          cache-dependency-path: pnpm-lock.yaml   # <-- no "./"

      - uses: pnpm/action-setup@v4              # installs pnpm CLI
        with:
          version: 9          # or "latest"
          run_install: false  # we run install ourselves

      # ---------- install & build ----------
      - run: pnpm install --frozen-lockfile      # single, reliable install
      - run: pnpm run build                      # vite/tsc build
      - run: pnpm run build-storybook            # produce storybook-static

      # ---------- git / version bump ----------
      - run: |
          git config --global user.email "contact@swiftgum.com"
          git config --global user.name "github-actions[bot]"
      - run: |
          tag=$(npm version patch -m 'Bump version to %s [skip ci]')
          echo "tag=${tag#v}" >> "$GITHUB_OUTPUT"
        id: version

      # ---------- release & publish ----------
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          body: "Release ${{ steps.version.outputs.tag }}. Check it out on [NPM ➡️](https://www.npmjs.com/package/@swiftgum/pdfreader/v/${{ steps.version.outputs.tag }})."

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git push origin --follow-tags

      # ---------- deploy Storybook to GH Pages ----------
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
